sudo: false

language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.1
    - extra-android-m2repository
    - extra-android-support

script:
  - bash ./gradlew okbuck installBuck &&
    ./buck build appDevDebug appDevRelease appProdDebug appProdRelease another-appDebug another-appRelease &&
    ./buck test &&
    ./buck project

notifications:
  email: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/
