language: java
jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/android-sdk-dl
    - $HOME/android-sdk
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
  - master

env:
  global:
    - ANDROID_HOME="$HOME/android-sdk"
    - SKIP_OKBUCK=true
    - EXTRA_OKBUCK_ARGS="--quiet --stacktrace"
  matrix:
    - BUILD_CMD=build
    - BUILD_CMD=lint
    - BUILD_CMD=test

install:
  - if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > $HOME/android-sdk-dl/sdk-tools.zip ; fi
  - unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $HOME/android-sdk

  - yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses

  - $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools' > /dev/null
  - $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;28.0.3' > /dev/null
  - $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-28' > /dev/null

script:
  - ./tooling/ci/build_cmd.sh

notifications:
  email: false
