name: CI

on: [push, pull_request]

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    env:
      SKIP_OKBUCK: true
      EXTRA_OKBUCK_ARGS: "--quiet --stacktrace"
      EXTRA_BUCK_ARGS: "-v 0"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [1.8, 11]
        build_cmd: [build, lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Update Android SDK Components
        run: sdkmanager platform-tools build-tools;30.0.0 platforms;android-29
      - name: Run ${{ matrix.build_cmd }}
        run: ./tooling/ci/build_cmd.sh ${{ matrix.build_cmd }}
